### ISSUE TITLE
我已提交新的合并请求，对于这事表示歉意！

### ISSUE THREAD

**Issue by ghost** [yujiandong/yii2-authclient#1]
![1](https://cloud.githubusercontent.com/assets/1439155/14806378/0400bb84-0ba5-11e6-98b2-7687706c4511.png)
![2](https://cloud.githubusercontent.com/assets/1439155/14806379/040c06f6-0ba5-11e6-9fc1-ee031fff0dd1.png)
![3](https://cloud.githubusercontent.com/assets/1439155/14806380/0411620e-0ba5-11e6-8b79-4f32a910662d.png)

以上是我用的代码蓝本，没有先搜索就用了，对此表示歉意。

**Comment by yujiandong** [comment]
恩，接受你的道歉。
希望下次能考虑周全，这种事给外国人印象很不好。

**Comment by ghost** [comment]
我都删除了，你自己来吧，网络暴力受不了
